// Pricing-calculator share helpers. Lets the architect open the BOM's SKU
// list directly inside Azure Pricing Calculator / AWS Pricing Calculator so
// the customer can verify against the canonical source.
//
// Azure: emits a `.pricingcalc.json` import file the calculator accepts via
//        the Saved Estimates → Import flow.
// AWS:   emits a CSV matching the calculator's Bulk Estimate Import schema.

import type { BomLineItem } from "@/lib/exporters/bom-xlsx";

export type CalculatorExport = {
  filename: string;
  contentType: string;
  body: string;
};

/**
 * Azure Pricing Calculator import file. Format reverse-engineered from
 * https://azure.microsoft.com/en-us/pricing/calculator/ "Export estimate"
 * — JSON with `estimateName`, `currency`, `regions`, and an array of
 * resource entries (`serviceFamily`, `region`, `sku`, `quantity`).
 *
 * We emit a structural skeleton; the calculator's UI will resolve the
 * concrete SKU records on import. Architects can then adjust quantities
 * + add commitments inside the calculator before sharing with the customer.
 */
export function exportAzureCalculatorJson(
  lineItems: BomLineItem[],
  opts: { estimateName: string; region?: string; currency?: string },
): CalculatorExport {
  // Group VM line items (workload section) for the calculator.
  const vmItems = lineItems
    .filter((l) => l.section === "workload" && l.category === "Compute")
    .map((l) => ({
      serviceFamily: "Compute",
      serviceName: "Virtual Machines",
      region: l.region || opts.region || "Malaysia West",
      productName: l.serviceType,
      sku: extractSku(l.description) ?? l.serviceType,
      quantity: 1,
      monthlyHours: 730,
      monthlyUsdEstimate: l.monthlyUsd,
      notes: l.customName,
    }));

  const lzItems = lineItems
    .filter((l) => l.section === "landing_zone")
    .map((l) => ({
      serviceFamily: l.category,
      serviceName: l.serviceType,
      region: l.region || opts.region || "Malaysia West",
      productName: l.serviceType,
      sku: l.customName || l.serviceType,
      quantity: 1,
      monthlyUsdEstimate: l.monthlyUsd,
      notes: l.description,
    }));

  const body = JSON.stringify({
    estimateName: opts.estimateName,
    currency: opts.currency ?? "USD",
    regions: [opts.region ?? "Malaysia West"],
    resources: [...vmItems, ...lzItems],
    note: "Generated by the Noventiq Multicloud Agent. Open in Azure Pricing Calculator → Saved Estimates → Import.",
    schemaVersion: 1,
  }, null, 2);

  return {
    filename: `${slug(opts.estimateName)}.azurepricing.json`,
    contentType: "application/json",
    body,
  };
}

/**
 * AWS Pricing Calculator CSV (Bulk Estimate Import schema). Headers based
 * on the public sample at https://calculator.aws/#/estimate/import.
 */
export function exportAwsCalculatorCsv(
  lineItems: BomLineItem[],
  opts: { estimateName: string; region?: string },
): CalculatorExport {
  const region = opts.region || "ap-southeast-5";
  const rows: string[] = [];
  rows.push([
    "Group hierarchy",
    "Description",
    "Region",
    "Service",
    "Instance type / SKU",
    "Quantity",
    "Hours per month",
    "Monthly USD (estimate)",
    "Notes",
  ].map(csvQuote).join(","));

  const allItems = lineItems.filter((l) => l.section === "workload" || l.section === "landing_zone");
  for (const l of allItems) {
    rows.push([
      l.section === "workload" ? "Workloads" : "Landing Zone",
      l.customName || l.serviceType,
      l.region || region,
      l.serviceType,
      extractSku(l.description) ?? l.serviceType,
      "1",
      l.section === "workload" && l.category === "Compute" ? "730" : "",
      String(l.monthlyUsd),
      (l.description || "").slice(0, 200),
    ].map(csvQuote).join(","));
  }

  return {
    filename: `${slug(opts.estimateName)}.awscalculator.csv`,
    contentType: "text/csv",
    body: rows.join("\n") + "\n",
  };
}

function csvQuote(v: string): string {
  if (v.includes(",") || v.includes('"') || v.includes("\n")) {
    return `"${v.replace(/"/g, '""')}"`;
  }
  return v;
}

function slug(s: string): string {
  return s.replace(/[^a-zA-Z0-9]+/g, "-").replace(/^-+|-+$/g, "").toLowerCase() || "bom";
}

// "1 D2s v5 (2 vCPU, 8 GB) 3-yr reserved, Windows" → "D2s v5"
// "Standard_D4s_v5, 4 vCPU, 16 GB, PAYG, Linux" → "D4s_v5" (with underscore)
function extractSku(description: string | null | undefined): string | null {
  if (!description) return null;
  // (?:^|[\s_]) handles both whitespace and underscore as leading boundary
  // because \b doesn't fire between underscores in Standard_D4s_v5.
  const azure = description.match(/(?:^|[\s_])((?:D|E|F|B|M)\d+s?[\s_]*v\d+)\b/i);
  if (azure) return azure[1];
  const aws = description.match(/\b((?:m|r|c|t)\d+\.[a-z0-9]+)\b/i);
  if (aws) return aws[1];
  return null;
}
